[package]
name = "crypt_rust_server"
version = "0.1.0"
authors = ["phage <IDAGod@protonmail.com>"]

[dependencies.mio]
version = "0.7"
features = ["os-poll", "tcp"]

[dependencies.rustls]
version = "0.17.0"

